In [89]:
#######################################################################################################
           # ESTABLISHING CONNECTION
#######################################################################################################

import tweepy as tp
import numpy
from tweepy import Cursor
import json
import jsonlines
import pandas


print("Main Start")
apiKey = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
apiSecretKey = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
accessToken = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
accessTokenSecret = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

auth = tp.OAuthHandler(apiKey,apiSecretKey)
auth.set_access_token(accessToken,accessTokenSecret)
auth_api = tp.API(auth)
#print (auth)
username = "midasIIITD"
print("Getting data for - ", username)
item = auth_api.get_user(username)
# print(item.name)
# print(item.screen_name)
# print(item.description)
# print("statuses_count: " + str(item.statuses_count))
# print("friends_count: " + str(item.friends_count))
# print("followers_count: " + str(item.followers_count))
# print(item.created_at)

Main Start
Getting data for -  midasIIITD

In [85]:
#######################################################################################################
            # GETTING DATA INTO LIST
#######################################################################################################

liss = {}
for status in Cursor(auth_api.user_timeline, id=username).items():
    liss[counter] = status._json

23 23 23 304 1

In [86]:
#######################################################################################################
        # DUMPING DATA INTO JSON FILE
#######################################################################################################

with open("data_file.json", "w") as write_file:
    json.dump(liss , write_file)

In [87]:
#######################################################################################################
           # RETRIVE DATA FROM JSON FILE AND PRINT IN TABLE
#######################################################################################################

import pandas
with open('data_file.json') as json_file:  
    data = json.load(json_file)
 
text = []
date=[]
like=[]
retw=[]
img=[]
for i in range(0,len(data)):
    key = str(i)
    text.append(data[key]['text'])
    date.append(data[key]['created_at'])
    like.append(data[key]['favorite_count'])
    retw.append(data[key]['retweet_count'])
    count  = 0 
    if 'extended_entities' in data[key].keys():
        #print('yes')
        
        #print(data[key]['extended_entities']['media'])
        for media in data[key]['extended_entities']['media']:
                if media['type'] == 'photo':
                    
                    count += 1
                    #print(count)
    img.append(count)
final_list=[]
final_list.append(text)
final_list.append(date)
final_list.append(like)
final_list.append(retw)
final_list.append(img)

final_list = list(map(list, zip(*final_list)))

headings = ["Text of tweet" , "Date & Time" , "# of likes" , "# of retweets" , "# of images"]

pandas.DataFrame(final_list , columns=headings)

,Text of tweet,Date & Time,# of likes,# of retweets,# of images
0,@IEEEBigMM19 @ACMMM19 and 6 days left for work...,Tue Mar 26 05:54:49 +0000 2019,0,0,0
1,RT @IEEEBigMM19: Hurry Up!\n6 Days left for Ab...,Tue Mar 26 05:50:10 +0000 2019,0,3,0
2,Congratulations @midasIIITD students Simra Sha...,Mon Mar 25 13:01:57 +0000 2019,14,1,0
3,The last date for submitting a solution for th...,Sun Mar 24 18:44:01 +0000 2019,8,3,0
4,RT @IIITDelhi: @IIITDelhi invites application ...,Sun Mar 24 18:26:02 +0000 2019,0,4,0
5,One more week is left to submit the workshop p...,Sun Mar 24 11:34:27 +0000 2019,4,0,0
6,RT @IEEEBigMM19: We are honored to have Dr. Ch...,Sun Mar 24 06:23:37 +0000 2019,0,5,0
7,RT @IEEEBigMM19: Distinguished researchers Dr....,Sun Mar 24 06:23:14 +0000 2019,0,3,0
8,@IEEEBigMM19 is also available on Facebook now...,Wed Mar 20 08:19:24 +0000 2019,1,1,0
9,RT @IEEEBigMM19: BigMM 2019 : IEEE BigMM 2019 ...,Wed Mar 20 02:40:07 +0000 2019,0,5,0
10,BigMM 2019 : IEEE BigMM 2019 â€“ Call for Worksh...,Mon Mar 18 02:27:47 +0000 2019,6,3,0
11,"Congratulations @midasIIITD team, Rohan, Prady...",Sun Mar 17 14:22:04 +0000 2019,15,4,0
12,We have emailed the task details to all shortl...,Sat Mar 16 14:06:56 +0000 2019,7,0,0
13,IEEE BigMM 2019 - Call for Workshop Proposals....,Sat Mar 16 09:20:29 +0000 2019,1,1,0
14,"Congratulations! Arijit, Ramit, @debanjanbhucs...",Sat Mar 16 09:14:58 +0000 2019,7,2,0
15,We will be releasing a very interesting task t...,Sat Mar 16 05:13:14 +0000 2019,7,2,0
16,RT @hcdiiitd: Last day to register for #Portfo...,Wed Mar 13 17:09:44 +0000 2019,0,2,0
17,@ACMMM19 @sigmm @TheOfficialACM @acmmmsys @ACM...,Wed Mar 13 04:11:24 +0000 2019,1,0,0
18,RT @ACMMM19: The paper deadline is approaching...,Wed Mar 13 04:06:04 +0000 2019,0,13,0
19,RT @kaggle: Bookmark this amazing library of i...,Tue Mar 12 17:43:44 +0000 2019,0,67,0
20,Awesome members of our @midasIIITD team who ar...,Tue Mar 12 14:37:55 +0000 2019,16,4,0
21,"@saanidhi @ACMMM19 Before Friday, 15th March.",Mon Mar 11 14:58:30 +0000 2019,0,0,0
22,We are glad to inform that Adobe is launching ...,Mon Mar 11 12:02:42 +0000 2019,4,0,0
23,We will email tasks to all shortlisted candida...,Mon Mar 11 11:54:38 +0000 2019,3,0,0
24,@ACMMM19 @ACM_MM2018 @acmmm17 @sigmm @ACM Less...,Mon Mar 11 06:22:12 +0000 2019,1,1,0
25,RT @kdnuggets: Face Recognition using One-Shot...,Mon Mar 11 06:17:20 +0000 2019,0,64,0
26,@AvinashSwamina2 @IIITDelhi No. They will be g...,Fri Mar 08 13:22:07 +0000 2019,1,0,0
27,We are in the process of finalizing the shortl...,Fri Mar 08 13:15:34 +0000 2019,8,4,0
28,@ylecun @NilayShri @the_dhumketu @debanjanbhuc...,Wed Mar 06 13:44:11 +0000 2019,3,0,0
29,RT @kdnuggets: Python Data Science for Beginne...,Wed Mar 06 11:12:30 +0000 2019,0,22,1
...,...,...,...,...,...
274,RT @TensorFlow: TensorFlow 1.10.0 has been rel...,Thu Aug 09 05:59:57 +0000 2018,0,265,0
275,@midasIIITD is looking for motivated IIITD MTe...,Wed Aug 08 11:30:56 +0000 2018,2,1,0
276,@IIITDelhi @ponguru @RatnRajiv The results of ...,Wed Aug 08 05:53:48 +0000 2018,3,1,1
277,RT @IIITDelhi: @midasIIITD has secured rank 1 ...,Wed Aug 08 05:45:58 +0000 2018,0,1,0
278,RT @kdnuggets: Comparison of Top 6 Python NLP ...,Tue Aug 07 07:16:33 +0000 2018,0,40,1
279,Check more details of the 20th IEEE Internatio...,Tue Aug 07 02:05:12 +0000 2018,1,1,0
280,MR2AMC@ISM 2018 will be organized by @RatnRaji...,Tue Aug 07 01:58:49 +0000 2018,1,1,0
281,"Our workshop proposal named, ""MR2AMC: Multimod...",Tue Aug 07 01:50:33 +0000 2018,1,1,0
282,@NUSComputing Congratulations Abdelhak and Pro...,Mon Aug 06 17:48:23 +0000 2018,0,0,0
283,RT @goodfellow_ian: One of the most anticipate...,Mon Aug 06 17:46:59 +0000 2018,0,103,1
284,@the_dhumketu Great to have you in @midasIIITD,Mon Aug 06 06:06:47 +0000 2018,0,0,0
285,Congratulation @soujanyaporia for being appoin...,Fri Aug 03 05:56:33 +0000 2018,6,1,0
286,@IIITDelhi @the_dhumketu Thanks team @midasIII...,Wed Aug 01 11:47:15 +0000 2018,5,1,1
287,RT @IIITDelhi: Congratulations @midasIIITD int...,Wed Aug 01 11:20:07 +0000 2018,0,4,0
288,RT @learning_pt: Profile of the 5 Indian under...,Wed Aug 01 05:06:47 +0000 2018,0,4,0
289,Have a look at the list of accepted papers in ...,Tue Jul 31 12:11:52 +0000 2018,1,0,0
290,RT @goodfellow_ian: https://t.co/hYiWI7ntyk Te...,Tue Jul 31 02:06:26 +0000 2018,0,264,0
291,RT @IIITDelhi: Congratulations Dr. @RatnRajiv ...,Mon Jul 30 07:30:51 +0000 2018,0,2,0
292,"RT @ylecun: Jitendra Malik, who directs FAIR-M...",Sat Jul 28 11:07:11 +0000 2018,0,57,0
293,RT @kdnuggets: .@Bloomberg launches free cours...,Sat Jul 28 06:14:09 +0000 2018,0,105,0
294,RT @TechAtBloomberg: Missed #PyLondinium18? Wa...,Sat Jul 28 06:13:48 +0000 2018,0,7,0
295,RT @IIITDelhi: We are delighted to announce th...,Sat Jul 28 04:08:21 +0000 2018,0,6,0
296,Get ready for the annual technical fest of @II...,Fri Jul 27 06:46:44 +0000 2018,3,2,0
297,Congratulations Dr. @RatnRajiv and team @midas...,Fri Jul 27 04:07:31 +0000 2018,8,2,0
298,Congratulations MIDAS @midasIIITD intern Prakh...,Wed Jul 25 05:14:35 +0000 2018,5,1,0
299,MIDAS@IIITD foundation. https://t.co/LKuzyBHzjm,Tue Jul 24 10:33:23 +0000 2018,2,1,0
300,It feels great to be the part of @IIITDelhi. h...,Tue Jul 24 10:12:34 +0000 2018,2,1,0
301,"Thank you, @toonzratn for designing the logo o...",Tue Jul 24 09:46:26 +0000 2018,4,1,1
302,We are on Facebook too. Like our page to get o...,Mon Jul 23 16:25:05 +0000 2018,3,1,0
303,MIDAS is a group of researchers at IIIT-Delhi ...,Mon Jul 23 12:53:15 +0000 2018,7,4,0